baseURL = "https://xieha.cn/"
languageCode = "zh-CN"
title = "微影随行"
theme = "oneblog"
author = "welog"
copyright = "© 2024 我的博客. All rights reserved."

# 分页设置
[pagination]
pagerSize = 10

# 主题参数
[params]
themeColor = "#ff5050"          # 主题主色调
logo_alt = "微影随行"     # Logo替代文本（可选）
slogan = "记录生活-记录美好"  # 网站副标题
switch = "on"                   # 是否开启首页banner
webtime = "2023"                # 网站创建年份
icp = "粤ICP备2024299131号"         # 备案号
wa = ""   # 公安备案号
logo = "/img/logo.png"                       # 网站logo
logoWhite = "/img/logo.png"                  # 白色logo（夜间模式用）
webthumb = ""                   # 网站缩略图（用于OGP）
imgSmall = "?imageView2/1/w/300/h/200/q/75"  # 缩略图处理参数
beCode = "on"                   # 是否开启代码高亮
customCSS = ""                  # 自定义CSS
customJS = ""                   # 自定义JS
disqusShortname = ""            # Disqus评论系统（留空则关闭）
defaultThumbnailField = "image"  # 强制使用image字段作为封面图

# 社交链接
[params.contact]
qq = "991391089"                # QQ号
weixin = "img/weixin.jpg"       # 微信二维码图片
email = "991391089@qq.com"      # 邮箱
github = "https://github.com/jawaylog"  # Github链接

# 首页banner配置
[[params.banner]]
link = "/posts/四川成都"
title = "四川成都"
thumb = "https://img.xieha.cn/i/2024/10/19/6712d71836ae1.webp"

[[params.banner]]
link = "/posts/小狮谷屋"
title = "小狮谷屋"
thumb = "https://img.xieha.cn/i/2024/10/19/6712d71a4d3ed.jpg"

[[params.banner]]
link = "/posts/邕城记"
title = "邕城记"
thumb = "https://img.xieha.cn/i/2024/12/09/6755eef805c87.jpg"

# 菜单配置
[[menu.main]]
name = "首页"
url = "/"
weight = 1
params.icon = "icon-home"

[[menu.main]]
name = "微文章"
url = "/archives"
weight = 2
params.icon = "icon-archives"

[[menu.main]]
name = "随笔录"
url = "/memo"
weight = 3
params.icon = "icon-archives"

[[menu.main]]
name = "微言语"
url = "/welog"
weight = 4
params.icon = "icon-archives"


[[menu.footer]]
name = "朋友圈"
url = "/rss"
weight = 5
params.icon = "icon-archives"

[[menu.footer]]
name = "伙伴们"
url = "/friends"
weight = 6
params.icon = "icon-archives"

[[menu.footer]]
name = "关于我"
url = "/about"
weight = 10
params.icon = "icon-archives"


# 代码高亮
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
  [markup.goldmark.renderer]
    unsafe = true  # 允许渲染原始HTML

